#!/bin/bash
# ENV Variables expected
# MESHERY_SERVER_BASE_URL
# UPLOAD_TYPE: can be "Kubernetes Manifest" | "Helm Chart" | "Docker Compose" | "Meshery Design" 
# PROVIDER_TOKEN: MESHERY provider token

# Get Meshery pattern file as escaped YAML string
MESHERY_PATTERN_FILE=$(pattern_file=$(cat __intermediate_file.yml) node ./action/normalize-configuration-file/index.js)

# Convert to URI-encoded string
UPLOAD_TYPE=$(printf %s "$UPLOAD_TYPE" | jq -sRr @uri)

# Perform the curl request and store response in a variable
RESPONSE=$(curl -s "$MESHERY_SERVER_BASE_URL/api/pattern/import" \
  -H 'Accept: */*' \
  -H 'Connection: close' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H "Cookie: meshery-provider=Meshery; token=$PROVIDER_TOKEN;" \
  --data-raw "{ \"name\": \"autogenerated\", \"file_name\" : \"manifest.yml\",  \"file\" :$MESHERY_PATTERN_FILE }" \
  --compressed)

# Append the response to log.txt
echo "$RESPONSE" >> log.txt

# Extract and return the ID
echo "$RESPONSE" | jq -r '.[0].id'
