name: 'MeshMap Snapshot With URL-Upload'
on: # rebuild any PRs and main branch changes
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      fileURL: 
        description: Remote public accessible file URL
        required: true
        type: string
    outputs:
      resource_url:
        description: "The URL of the generated resource."
        value: ${{ jobs.MeshMapScreenshot.outputs.resource_url }}

jobs:
  MeshMapScreenshot: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    outputs:
      resource_url: ${{ steps.test_result.outputs.resource_url }}
    steps:
      - name: Set PR number # To comment the final status on the Pull-request opened in any repository
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - uses: actions/checkout@v3 #this step would go and would be no longer needed to be written
        with:
          path: action
          repository: layer5labs/meshmap-snapshot
      - id: test_result
        uses: layer5labs/MeshMap-Snapshot@v0.0.8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # github's personal access token example: "ghp_...."
          providerToken: ${{ secrets.PROVIDER_TOKEN }} # Meshery Cloud Authentication token, signin to meshery-cloud to get one, example: ey.....
          prNumber: ${{ env.PULL_NO }} # auto-filled from the above step
          application_type: $ph_application_type # your application type, could be any of three: "Kubernetes Manifest", "Docker Compose", "Helm Chart"
          application_url: ${{ inputs.fileURL == '' && $ph_application_url || inputs.fileURL }}
          
        
