name: Kanvas Snapshot With URL-Upload
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:
    inputs:
      fileURL:
        description: Remote public accessible file URL
        required: true
        type: string
    outputs:
      resource_url:
        description: The URL of the generated resource.
        value: ${{ jobs.KanvasScreenshot.outputs.resource_url }}
jobs:
  KanvasScreenshot:
    runs-on: ubuntu-latest
    outputs:
      resource_url: ${{ steps.test_result.outputs.resource_url }}
    steps:
      - name: Set PR number
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          path: action
          repository: layer5labs/kanvas-snapshot
      - id: test_result
        uses: layer5labs/kanvas-snapshot@v0.2.16
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mesheryToken: ${{ secrets.MESHERY_TOKEN }}
          prNumber: ${{ env.PULL_NO }}
          application_type: $ph_application_type
          application_url: ${{ inputs.fileURL == '' && '$ph_application_url' || inputs.fileURL }}
      - uses: layer5labs/kanvas-snapshot@v0.2.35
